server:
  port: 8080

spring:
  application:
    name: webflux-api
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username: 77kkyu
    password: 1234

logging:
  level:
    org:
      springframework:
        r2dbc=DEBUG: DEBUG